### ISSUE TITLE
Content mirror request

### ISSUE THREAD

**Issue by sb-child** [viva-la-vita/wiki#11]
## 背景
您好，我们想要以源代码(源文件)的方式定期镜像此知识库的内容用于公开的个人备份存档，但是我们发现知识库的内容是从私有的服务中拉取的。

## 可能的解决方案
如果可以的话，我们希望网站维护者可以公开内容部分的源代码(源文件)。

## 其他说明
如果不想公开的话，请关闭此issue ~~<sub> (小声呜呜 </sub>~~

**Comment by tansongchen** [comment]
为了解耦内容生产和网站生成我们把内容迁移到了 CMS 中，但仍然可以通过 https://api.viva-la-vita.org 访问。下面是两个例子：

```js
const axios = require('axios');

axios.get(`https://api.viva-la-vita.org/api/navigation/render/1`, {
  params: {
    type: 'TREE'
  }
}).then(({ data }) => {
  console.log(data);
});

axios.get(`https://api.viva-la-vita.org/api/articles/10`).then(({ data }) => {
  console.log(data);
});
```

第一个例子是以树状结构获取整个 wiki 站的内容，第二个例子是按给定的 article id 获取一篇文章的内容。我们近期也会将 API 的使用方法添加到主页站的文档中。

使用这些内容时请注意遵守 CC-BY-SA 4.0 协议。

**Comment by tansongchen** [comment]
请求的方法已经更新到[主页](https://viva-la-vita.org/introduction/api/)。

**Comment by tansongchen** [comment]
@sb-child 刚刚在现有的 API 基础上进一步封装为 SDK，一行代码即可下载文档，具体请参见[生如夏花 SDK](https://github.com/viva-la-vita/sdk)。
