### ISSUE TITLE
邮件激活错误

### ISSUE THREAD

**Issue by qingzhixing** [viva-la-vita/wiki#12]
我试用Prtonmail和163邮箱注册了两个账号，都在激活邮件环节无法进行，并没有邮件发送过来，我的一位朋友也反馈有这个问题，所以我来发一个issue（）

**Comment by tansongchen** [comment]
现在应该已经修复了。另外，这个仓库是知识库的，论坛的问题可以在 https://github.com/viva-la-vita/bbs 提出。
